# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

servers=[
      {
        :hostname => "puppet-server",
        :ip => "192.168.100.10",
        :box => "ubuntu/xenial64",
        :ram => 1024,
        :cpu => 1
      },
      {
        :hostname => "puppet-agent",
        :ip => "192.168.100.11",
        :box => "ubuntu/xenial64",
        :ram => 1024,
        :cpu => 1
      }
    ]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
	    end
            node.vm.provision :shell, :inline => "apt-get update && apt-get -y dist-upgrade", :privileged => true
        end
     end
end
